# This is a simple network configuration file

[[routers]]
address = "127.0.0.1"
neighbors = [

    { address = "127.0.0.2", cost = 1 },
    { address = "127.0.0.3", cost = 3 },
    { address = "127.0.0.4", cost = 7 }
]
    
[[routers]]
address = "127.0.0.2"
neighbors = [
    { address = "127.0.0.1", cost = 1 },
    { address = "127.0.0.3", cost = 1 }
]

[[routers]]
address = "127.0.0.3"
neighbors = [
    { address = "127.0.0.1", cost = 3 },
    { address = "127.0.0.2", cost = 1 },
    { address = "127.0.0.4", cost = 2 }
]

[[routers]]
address = "127.0.0.4"
neighbors = [
    { address = "127.0.0.1", cost = 7 },
    { address = "127.0.0.3", cost = 2 }
]
